name: Examples Integration
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: ["0.15.4"]
        target: ["python", "csharp", "java", "typescript", "go"]
    container:
      image: docker.mirror.hashicorp.services/hashicorp/jsii-terraform
    env:
      TF_PLUGIN_CACHE_DIR: "/root/.terraform.d/plugin-cache"
      CHECKPOINT_DISABLE: "1"
    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: |
          yarn install
      - name: compile
        run: |
          yarn build
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
      - name: create bundle
        run: yarn package
      - name: bootstrap plugin cache
        run: yum install -y jq && yarn bootstrap-plugin-cache
        env:
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
      - name: examples integration tests
        run: yarn examples:integration:${TEST_TARGET}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          TEST_TARGET: "${{ matrix.target }}"
          TERRAFORM_BINARY_NAME: "terraform${{ matrix.terraform }}"
          MAVEN_OPTS: "-Xmx3G"
